# Generated by Django 4.1.3 on 2022-11-02 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Key",
            fields=[
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "id",
                    models.PositiveBigIntegerField(
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="WireGuard Key ID",
                    ),
                ),
                (
                    "associated_ip",
                    models.GenericIPAddressField(verbose_name="Associated IP"),
                ),
            ],
            options={
                "verbose_name": "Key",
                "verbose_name_plural": "Keys",
                "db_table": "key",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "id",
                    models.PositiveBigIntegerField(
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="User ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, verbose_name="Username")),
                (
                    "key",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="core.key",
                        verbose_name="Key",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "tg_user",
            },
        ),
    ]
